In [2]:
%run C:/__PYP/__COMMON/ugenejupyterlib/firstcell.ipynb
%run C:/__PYP/__COMMON/ugenejupyterlib/datacell.ipynb
    
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.graph_objects as go

import plotly.io as pio
pio.renderers
pio.renderers.default = "browser"

@
        # platform.node()='MH507192'
        # datetime.now()=datetime.datetime(2020, 12, 15, 15, 23, 59, 630190)
        # sys.version='3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]'

In [3]:
# As a rule, texttemplate and hovertemplate can access any attribute at the trace level 
# i.e. attributed of go.Bar() in this case. 
# So x, y, text, and customdata are accessible:

ccc=\
"""
===========================================================================================
[NOTE] x, y, customdata, text
===========================================================================================

[singular] x, y refers to a pair of coord (x0, y0), 
[plural] x, y, holding two arrays of xs and ys, which is used in go.Bar(x=array, y=array, ...)
    
x, y, in singular senese, are: per point, or akin to, iteration using x or y thru xs and ys:
    "for x, y in the_collection_of_all_xs_and_ys_in_this_trace/plot:"
    "for every point in the trace, access/doSomething with that specific point's x and y"

customdata/text is a thrid x or y here (singular sense AND plural sense)
so "for every tuple of (x, y, customdata) in the trace/plot: do something"
THE KEY HERE IS customdatas shares the same SEQUENCE as xs and ys (plural sense)

customdata/text is the only way of holding some lookup info from another df or external source.
there is no way to do myfoo() in a trace, instead, use myfoo() to prepare the customdata
"""

import plotly.graph_objects as go

go.Figure(go.Bar(
    x=          ['a',        'b',       'c'],
    y=          [ 1,          2,         3 ],
    customdata= ['c0',       'c1',      'c2'],
    
    # Notice above how a, 1 and c0 formed a tuple of (a, 1, c0)
    # and how they are accessed below:
    
    hovertemplate="x is %{x}, y is %{y}, customdata is %{customdata}",
        # hover template is applied to every single point, or bar in this case
        # the first bar will be ('a', 1, 'c0')
    
    texttemplate="x is %{x}, y is %{y}, customdata is %{customdata}",
    
    textposition="auto"
))

In [51]:
ccc=\
"""
BEFORE WE CAN GO ANY FURTHER, INTRODUCING A VERY IMPORTANT CONCEPT, 
DF TO DICT
AS JAVASCRIPT ONLY HAS LIST AND DICT

=====================================================================
df.to_dict(str)
=====================================================================
str {‘dict’, ‘list’, ‘series’, ‘split’, ‘records’, ‘index’}
Determines the type of the values of the dictionary.

‘dict’ (default) : dict like {column -> {index -> value}}

‘list’ : dict like {column -> [values]}

‘series’ : dict like {column -> Series(values)}

‘split’ : dict like {‘index’ -> [index], ‘columns’ -> [columns], ‘data’ -> [values]}

‘records’ : list like [{column -> value}, … , {column -> value}]

‘index’ : dict like {index -> {column -> value}}

Abbreviations are allowed. s indicates series and sp indicates split.
"""

df = pd.DataFrame(dict(
    col0=["a","b"], col1=[1,2], col2=["XXX", "YYY"]
))

df

df.to_dict('dict') # 'dict' is the default option

# you access by dct[coln][index]
df.to_dict('dict')['col2'][0]

df[['col0']].to_dict('dict')


try:
    df['col0'].to_dict('dict') # this won't work, because df['col0'] is a sr, not a df
except Exception as eee:
    eee

    
######################################################################
# HOWEVER, UNFORTUNATELY, PLOTLY'S customdata CAN NOT USE nested DICT
# have to use to_dict('records') format
######################################################################
df[['col0']].to_dict('records')    
df[['col0', 'col1', 'col2']].to_dict('records')

# and you access by dct[index][col]
# basically, a per-row dictionary, 
#     like how you build up a new df with a sr from dict, while itertupleing an old df
df.to_dict('records')[0]['col2']

  col0  col1 col2
0    a     1  XXX
1    b     2  YYY

{'col0': {0: 'a', 1: 'b'}, 'col1': {0: 1, 1: 2}, 'col2': {0: 'XXX', 1: 'YYY'}}

'XXX'

{'col0': {0: 'a', 1: 'b'}}

TypeError("unsupported type: <class 'str'>")

[{'col0': 'a'}, {'col0': 'b'}]

[{'col0': 'a', 'col1': 1, 'col2': 'XXX'},
 {'col0': 'b', 'col1': 2, 'col2': 'YYY'}]

'XXX'

In [66]:
ccc=\
"""
=====================================================================
customdata can be either a list or list of lists
or a list of dicts

In this example, we will show a dictionary example.
NOT PRACTICAL, but very illustrative.
=====================================================================
"""

import plotly.graph_objects as go

# [NOTE] df and ref doesn't need to share the same index nor the sequence of the "lookupkey"
#        proper sequence only needs to be preserved while building up customdata later
df = pd.DataFrame({
    "time"        : ['jan',     'feb',     'mar'],
    "data"        : [ 1,         2,          3, ], 
    "lookupkey"   : ["XXX",     "YYY",     "ZZZ"],
})

ref = pd.DataFrame({
    "lookupkey"   : ["YYY",     "XXX",     "ZZZ"],
    "lookupinfoA" : ["y>A",     "x>A",     "z>A"],
    "lookupinfoB" : ["y>B",     "x>B",     "z>B"],
})

df
ref


######################################################################
# BUILDING customdata, 
# iterate using the df, not ref, to maintain sequence

# the purpose here is to build up a list of dict, that is in the same sequence as df
#     "time"     : ['jan',        'feb',         'mar'],
#     "data"     : [ 1,            2,              3, ], 
#     "lookupkey": ["XXX",        "YYY",         "ZZZ"],
        
#     customdata :[{infoA:xval   {infoA:yval    {infoA:zval  ] # pseudo syntax
#                   infoB:xval},  infoB:yval},   infoB:zval},
######################################################################

customdata = []
for key in df['lookupkey'].values: # MAKE SURE to build it iterating thru df, not ref
    
    tempdict={}
    for i, col in enumerate(info_of_interests:=["lookupinfoA", "lookupinfoB"]):
        tempdict[info_of_interests[i]] = ref.loc[
            ref["lookupkey"]==key, 
            info_of_interests[i],
        ]
    customdata.append(
        tempdict
    )


go.Figure(go.Bar(
    x= df['time'],
    y= df['data'],
    customdata= customdata,
    
    hovertemplate="x is %{x}, y is %{y}, customdata is %{customdata.lookupinfoA}",
    texttemplate="x is %{x}, y is %{y}, customdata is %{customdata.lookupinfoB}",
    
    textposition="auto"
))

  time  data lookupkey
0  jan     1       XXX
1  feb     2       YYY
2  mar     3       ZZZ

  lookupkey lookupinfoA lookupinfoB
0       YYY         y>A         y>B
1       XXX         x>A         x>B
2       ZZZ         z>A         z>B

In [69]:
PHILOSOHPICAL=\
"""
==========================================================================================================================================
THE LESSON LEARNT: the proper approach of plotlying a df:
    [1] use a merged df with all information you will ever need
    
    [2] for a single trace, pick 2 cols as x and y 
        x = col with cell values that are used as labels on x axis, like Timestamp,
        y = col with cell values decribing a count/howmuch, 
            determines height of bar, where scatter point is, ie, shape of the plot, nothing to do with y label.
            
    [2.1] add multiple trace:
        pick the same x
        y = another col with count/howmuch
        y's col's column name will be the category
        
    [3] store the rest of the df in customdata,
        which already share the same sequence,
        no need to worry about building up a customdata in sequence, use to_dict('records')
==========================================================================================================================================
"""

df = pd.DataFrame({
    "time"        : ['jan',     'feb',     'mar'],
    "data"        : [ 1,         2,          3, ], 
    "lookupkey"   : ["XXX",     "YYY",     "ZZZ"],
})

ref = pd.DataFrame({
    "lookupkey"   : ["YYY",     "XXX",     "ZZZ"],
    "lookupinfoA" : ["y>A",     "x>A",     "z>A"],
    "lookupinfoB" : ["y>B",     "x>B",     "z>B"],
})

df = pd.merge(left=df, right=ref, how='left', on="lookupkey")
df

go.Figure(go.Bar(
    x= df['time'],
    y= df['data'],
    customdata= df[["lookupinfoA", "lookupinfoB"]].to_dict("records"),
    
    hovertemplate="x is %{x}, y is %{y}, customdata is %{customdata.lookupinfoA}",
    texttemplate="x is %{x}, y is %{y}, customdata is %{customdata.lookupinfoB}",
    
    textposition="auto"
))

  time  data lookupkey lookupinfoA lookupinfoB
0  jan     1       XXX         x>A         x>B
1  feb     2       YYY         y>A         y>B
2  mar     3       ZZZ         z>A         z>B

In [19]:
PHILOSOHPICAL=\
"""
==========================================================================================================================================
[CASE] df and ref can NOT be merged

in this code snip however, df and ref are completely different
the hover text is to look up info not based on x nor y, but the colname itself
==========================================================================================================================================
"""

df = pd.DataFrame(
    data = {
        "cat0"   : [2, 1, 1, 3, np.nan],
        "cat1"   : [1, 0, np.nan, 4, 3], 
        "cat2"   : [1, 3, 1, np.nan, 1],
    },
    index = pd.date_range(start='1/1/2018', periods=5, freq="M")
)



ref = pd.DataFrame({
    "lookupkey"   : ["cat0",    "cat1",    "cat2"],
    "lookupinfoA" : ["y>A",     "x>A",     "z>A"],
    "lookupinfoB" : ["y>B",     "x>B",     "z>B"],
})
fig = go.Figure(
    data=[
        go.Bar(
            name=coln, x=df.index, y=df[coln],
            # coln means columnName
            
            customdata = ref.loc[ref['lookupkey']==coln, :].to_dict('records') *len(df.index),
            texttemplate = '%{customdata.lookupinfoB}' + '%{customdata.lookupinfoA}',            
            textposition="auto",
    
        ) for coln in df.columns
    ],  
)

df
ref

fig = fig.update_layout(barmode='stack')
fig.show()

            cat0  cat1  cat2
2018-01-31   2.0   1.0   1.0
2018-02-28   1.0   0.0   3.0
2018-03-31   1.0   NaN   1.0
2018-04-30   3.0   4.0   NaN
2018-05-31   NaN   3.0   1.0

  lookupkey lookupinfoA lookupinfoB
0      cat0         y>A         y>B
1      cat1         x>A         x>B
2      cat2         z>A         z>B